language: node_js
sudo: required
node_js: 14.17.0
cache: npm
script:
  - npm run build
install:
  - yarn
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main
